server:
  port: 8083

spring:
  datasource:
    username: root
    password: abcd1234
    url: jdbc:mysql://localhost:3306/forum
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/home/thesky/uploadfiles/forum/
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis:
  type-aliases-package: top.thesky341.bbsforum.entity
  mapper-locations: classpath:top/thesky341/bbsforum/mapper/*.xml

imgAbsolutePathPrefix: /home/thesky/uploadfiles/forum/


