spring:
  profiles:
    active: prod

---
server:
  port: 8083

spring:
  datasource:
    username: root
    password: abcd1234
    url: jdbc:mysql://localhost:3306/forum
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles: dev

mybatis:
  type-aliases-package: top.thesky341.bbsforum.entity
  mapper-locations: classpath:top/thesky341/bbsforum/mapper/*.xml

---

spring:
  datasource:
    username: root
    password: abcd1234
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles: prod

mybatis:
  type-aliases-package: top.thesky341.bbsforum.entity
  mapper-locations: classpath:top/thesky341/bbsforum/mapper/*.xml

server:
  port: 8085
